config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/index'
  
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            length: { minimum: 3, maximum: 25 },
            uniqueness: { case_sensitive: false }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  
  validates :email, presence: true, 
            length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action."
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted!"
    redirect_to articles_path
  end
  
  private
    def set_article
      @article = Article.find(params[:id])
    end
  
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end
  
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own article."
        redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully."
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated."
      redirect_to category_path(@category)
    else
      
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  private
    def category_params
      params.require(:category).permit(:name)
    end
  
    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "Only admins can perform this action."
        redirect_to categories_path
      end
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)  
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in."
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information."
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your acocunt was updated successfully."
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted."
    redirect_to users_path
  end
  
  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your own account."
        redirect_to root_path
      end
    end
  
    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admin users can perform this action."
        redirect_to root_path
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<div class="container">

  <% obj.each do |article| %>
  
    <div class="row justify-content-md-center">
  
      <div class="col-10">

       <div class="card">

        <div class="card-block">

          <div class="article-title">

            <%= link_to article.title, article_path(article), class: "card-link" %>

          </div>

          <div class="article-body">

            <%= truncate(article.description, length: 100) %>

            <div class="article-meta-details">

              <div class="card-footer">

                <small>Created by: <%= article.user.username if article.user %>,
                                    <%= time_ago_in_words(article.created_at) %> ago,
                                    last updated: <%= time_ago_in_words(article.updated_at) %> ago
                </small>

              </div>

            </div>

          </div>
          
          <% if article.categories.any? %>
          
            <p>Categories: <%= render article.categories %></p>
          
          <% end %>

          <div class="article-actions">
            
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>

              <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-sm btn-primary" %>

              <%= link_to "Delete this article", 
                          article_path(article), 
                          method: :delete, 
                          data: {confirm: "Are you sure you want to delete this article?"}, 
                          class: "btn btn-sm btn-danger" %>
            
            <% end %>

          </div>

         </div>

        </div>

      </div>
  
    </div>
  
  <% end %>
  
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
  <div class="form-group">
      
    <%= f.label :title, class: "col-form-label" %>
         
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
      
  </div>
    
  <div class="form-group">
      
    <%= f.label :description, class: "col-form-label" %>
     
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
  
  </div>

  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <%= content_tag_for(:div, @article, class: "form-check form-check-inline") do %>
      <% cb.label(class: "form-check-label") {cb.check_box(class: "form-check-input") + " " + cb.text} %>
    <% end %>
  <% end %>
    
  <div class="form-group">
    
    <%= f.submit class: "btn btn-primary btn-lg" %>
      
  </div>

<% end %>

<div class="row justify-content-md-center">
  
  <div class="col-12 col-md-auto">

    [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

  </div>
  
</div>
    

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">

  <h1 align="center">Listing all articles</h1>
  
  <div class="row justify-content-md-center pagination">
    
    <div class="col-10 col-md-auto">
      <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>
    
  </div>

  <%= render 'article', obj: @articles %>
  
  <div class="row justify-content-md-center pagination">
    
    <div class="col-10 col-md-auto">
      <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>
    
  </div>
  
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
  
  <h1 align="center">Title: <%= @article.title %></h1>

  <div class="card">

    <div class="card-block">
      
      <% if @article.user %>
      
      <ul class="listing">
      
        <div class="row center">

          <div class="col-md-4 offset-md-4">
            
            <li>Created by:</li>

            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

            <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>

            <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>

          </div>

        </div>

      </ul>
      
      <% end %>
      
      <h4 class="center"><strong>Description:</strong></h4>
      
      <hr>
      
      <%= simple_format(@article.description) %>
      
      <% if @article.categories.any? %>
      
        <p>Categories: <%= render @article.categories %></p>
      
      <% end %>

      <div class="article-actions">
        
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>

          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-sm btn-primary" %>

          <%= link_to "Delete this article", 
                      article_path(@article), 
                      method: :delete, 
                      data: {confirm: "Are you sure you want to delete this article?"}, 
                      class: "btn btn-sm btn-danger" %>
        
        <% end %>
        
        <%= link_to "View all articles", articles_path, class: "btn btn-sm btn-success" %>

      </div>
      
    </div>

  </div>
  
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
  <div class="form-group">
      
    <%= f.label :name, class: "col-form-label" %>
         
    <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
      
  </div>
    
  <div class="form-group">
    
    <%= f.submit class: "btn btn-primary btn-lg" %>
      
  </div>

<% end %>

<div class="row justify-content-md-center">
  
  <div class="col-12 col-md-auto">

    [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

  </div>
  
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container">
  
  <h1 align="center">Listing All Categories</h1>
  
  <div class="row justify-content-md-center pagination">
    
    <div class="col-10 col-md-auto">
      
      <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
      
    </div>
    
  </div>

  <% @categories.each do |category| %>

    <ul class="listing">
      
      <div class="row justify-content-md-center">
        
        <div class="col-6">
      
          <div class="card center">

            <div class="card-block">

              <li class="article-title">
                
                <%= link_to "#{category.name}", category_path(category) %>
              
              </li>
              
              <li>
                
                <small>
                  
                  <%= pluralize(category.articles.count, "article") %>
                
                </small>
                
              </li>

            </div>

          </div>
          
        </div>
        
      </div>
    
    </ul>
  
  <% end %>
  
  <div class="row justify-content-md-center pagination">
    
    <div class="col-10 col-md-auto">
      
      <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
      
    </div>
    
  </div>
  
</div>

app/views/categories/new.html.erb
<h1 align="center">Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container">

  <h1 align="center"><%= "Category: " + @category.name %></h1>
  
  <% if logged_in? and current_user.admin %>
  
    <div class="row justify-content-md-center">

      <span class="badge">

        <%= link_to "Edit Category Name", edit_category_path(@category) %>

      </span>

    </div>
  
  <% end %>
  
  <div class="row justify-content-md-center pagination">
    
    <div class="col-10 col-md-auto">
      
      <%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
      
    </div>
    
  </div>

  <%= render 'articles/article', obj: @category_articles %>
  
  <div class="row justify-content-md-center pagination">
    
    <div class="col-10 col-md-auto">
      
      <%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
      
    </div>
    
  </div>
  
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://www.udemy.com">The Complete Ruby on Rails Developer Course </a> by <a href="www.mashrurhossain.com">Mashrur Hossain</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  
  <% flash.each do |name, msg| %>

    <div class='alert alert-<%="#{name}" %> alert-dismissible fade show' role='alert'>

      <button type="button" class="close" data-dismiss="alert">&times;</button>

      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

    </div>

  <% end %>
  
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarCategoriesDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarCategoriesDropdownMenuLink">
          <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
          <% Category.all.each do |category| %>
            <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
          <% end %>
          <% if logged_in? and current_user.admin? %>
            <hr>
            <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav navbar-right">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarAdminProfileDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarAdminProfileDropdownMenuLink">
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About ME!</h1>

<p>I am a new web developer and iOS application writer. I love to code but lack vision and ideas. However, I am trying to improve on those two deficiencies and trying different things.</p>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  
  <h1 class="display-3">ALPHA BLOG</h1>
  
  <p class="lead jumbotext">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  
  <hr class="my-4">
  
  <p class="jumbotext" id="small_jumbo_text">It uses utility classes for typography and spacing to space content out within the larger container.</p>
  
  <p class="lead">
    
    <%= link_to "Sign up now", signup_path, class: "btn btn-success btn-lg btn-xlarge", role: "button" %>
    
  </p>
  
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

  <div class="alert alert-danger" role="alert">

    <h4 class="alert-heading">

      <%= pluralize(obj.errors.count, "error") %>
      prohibited this article from being saved:

    </h4>

    <ul><% obj.errors.full_messages.each do |msg| %>

      <li><%= msg %></li>

      <% end %>

    </ul>

  </div>
      
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
  <div class="form-group">
      
    <%= f.label :username, class: "col-form-label" %>
         
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
      
  </div>
    
  <div class="form-group">
      
    <%= f.label :email, class: "col-form-label" %>
     
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email address" %>
  
  </div>

<div class="form-group">
      
    <%= f.label :password, class: "col-form-label" %>
     
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
  
  </div>
    
  <div class="form-group">
    
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
      
  </div>

<% end %>

<div class="row justify-content-md-center">
  
  <div class="col-12 col-md-auto">

    [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

  </div>
  
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
  
  <h1 align="center">All Alpha Bloggers</h1>
  
  <div class="row justify-content-md-center pagination">
    
    <div class="col-10 col-md-auto">
      <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>
    
  </div>

  <%= @users.each do |user| %>

    <ul class="listing">
      
      <div class="row justify-content-md-center">
        
        <div class="col-6">
      
          <div class="card center">

            <div class="card-block">

              <li><%= link_to gravatar_for(user), user_path(user) %></li>

              <li class="article-title"><%= link_to user.username, user_path(user) %></li>

              <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
              
              <% if logged_in? and current_user.admin? %>
                <li><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user and all of the users articles?" } %></li>
              <% end %>

            </div>

          </div>
          
        </div>
        
      </div>
    
    </ul>

  <% end %>
  
  <div class="row pagination">
    
    <div class="col-10 col-md-auto">
      <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>
    
  </div>
  
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<p></p>
  
  <div class="center">
    
    <%= gravatar_for @user, size: 150 %>
    
  </div>
  
<p></p>

<h4 align="center"><%= @user.username %>'s articles</h4>

<div class="row justify-content-md-center pagination">
    
  <div class="col-10 col-md-auto">
    <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
    
</div>

<%= render 'articles/article', obj: @user_articles %>

<div class="row justify-content-md-center pagination">
    
  <div class="col-10 col-md-auto">
    <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
    
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>